cp -r ../CPlusPlusStarter/bin .
cp -r ../CPlusPlusStarter/build .
cp -r ../CPlusPlusStarter/src .
cp -r ../CPlusPlusStarter/.vscode .
cp -r ../CPlusPlusStarter/.gitignore .
cp -r ../CPlusPlusStarter/README.md .
cp -r ../CPlusPlusStarter/Makefile .
cp -r ../CPlusPlusStarter/LICENSE .
cp -r ../CPlusPlusStarter/copyFIles.sh .